### ISSUE TITLE
Changes needed to the format to be able to support "corner masters"

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/black-robo-cjk#128]
The current limitation of RoboCJK glyph-level designspaces is that for each axis, there is exactly one master. But often one needs a master at the maximum of *multiple* axes, such as in the Hangul subproject.

The limitation is caused by the fact that there is a one-on-one mapping from axes to variation masters:

-  a `robocjk.glyphVariationGlyphs` or `robocjk.fontVariationGlyphs` lib item is a dictionary, with axis names as keys, and each item *simultaneously* represents an axis definition and a variation master.

This needs to be separated. The structure will become similar to a (simplified) designspace file:

- A list of Axes, where each Axis has the following fields:
  - `name`
  - `minValue`
  - `maxValue`
- A list of Variation Glyphs sources, where each source has the following fields:
  - `location`: a dict specifying the "designspace" location, for example `{"wght": 1, "wdth": 1}` for a corner master.
  - `layerName`: the layer in which to find the outlines for this variation glyph, if any
  - deep component data

Perhaps the axes list could be stored under a new lib key `robocjk.axes`.

The existing `robocjk.glyphVariationGlyphs` and `robocjk.fontVariationGlyphs` will need to be converted from a dictionary to a list.

I would suggest to drop the distinction between glyph variations and font variations, although that's a separate issue. I'd suggest `robocjk.variationGlyphs` to cover both.

The details of how to do the intepolation based on this new structure is also a separate issue, but the `robocjk.project` code already supports doing it, using varLib as much as possible, and can serve as an example. But I can gladly discuss and help.

**Comment by justvanrossum** [comment]
Once this change will be planned, I would love to propose another change that can be done at the same time.

The `robocjk.deepComponent` lib items are currently structured like this (in yaml notation):
```yaml
robocjk.deepComponents:
  - name: DC_4E28_00
    coord:
      WGHT: 0.418
    rcenterx: 0
    rcentery: 0
    rotation: 0
    scalex: 1.0
    scaley: 0.9
    x: 0
    y: 37
```

I would love for the individual transform paramters to be grouped under a separate item, called "transform", like this:
```yaml
robocjk.deepComponents:
  - name: DC_4E28_00
    coord:
      WGHT: 0.418
    transform:
      rcenterx: 0
      rcentery: 0
      rotation: 0
      scalex: 1.0
      scaley: 0.9
      x: 0
      y: 37
```
